### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.psi.PsiManager because container is already disposed (container=Project(name=Plantagen.Ecommerce, containerState=DISPOSE_COMPLETED, componentStore=/Users/mkarapan/git_repository/improove/Plantagen.Ecommerce) (disposed))

### ISSUE THREAD

**Issue by mkarapan-improove** [smokeelow/intellij-sfcc#16]
IntelliJ build version: 2022.3 WS-223.7571.168
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 2022.3
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1023,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@551210ff,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.psi.PsiManager because container is already disposed (container=Project(name={name removed}, containerState=DISPOSE_COMPLETED, componentStore={path removed}) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:701)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:63

**Comment by smokeelow** [comment]
Hi, should be fixed in latest plugin version `2022.3.4`
