### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by iddemirjs** [smokeelow/intellij-sfcc#18]
IntelliJ build version: 2022.3.1 WS-223.8214.51
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 2022.3.5
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1003,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:802)
	at java.base/java.util.Timer.<init>(Timer.java:188)
	at java.base/java.util.Timer.<init>(Timer.java:170)
	at java.base/java.util.Timer.<init>(Timer.java:143)
	at io.divetek.sfcc.service.SiteScopeSettings$startListening$lambda$3$$inlined$runReadAction$1.compute(actions.kt:81)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:860)
	at io.divetek.sfcc.service.SiteScopeSettings.startListening$lambda$3(SiteScopeSettings.kt:182)
	at com.intellij.openapi.p

**Comment by smokeelow** [comment]
Hi, how many memory do you have for your IDE  ?
<img width="188" alt="image" src="https://user-images.githubusercontent.com/1822237/210334401-c23708af-d162-4a43-b568-b9e559d35e8a.png">
