### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.psi.PsiManager because container is already disposed (container=Project(name=carters.com, containerState=DISPOSE_COMPLETED, componentStore=H:\Projects\Carters\carters.com) (disposed))

### ISSUE THREAD

**Issue by Palko-Astound** [smokeelow/intellij-sfcc#22]
IntelliJ build version: 2022.3.2 WS-223.8617.44
OS: Windows 11
JDK: JetBrains s.r.o. 17.0.5
Plugin version: 2022.3.5
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,8,0,1194x934,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.serviceContainer.AlreadyDisposedException: Cannot create com.intellij.psi.PsiManager because container is already disposed (container=Project(name=carters.com, containerState=DISPOSE_COMPLETED, componentStore=H:\Projects\Carters\carters.com) (disposed))
	at com.intellij.serviceContainer.ContainerUtilKt.throwAlreadyDisposedError(containerUtil.kt:40)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:695)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:629)
	at com.intellij.psi.PsiManager.getInstance(PsiManager.java:25)

**Comment by smokeelow** [comment]
@Palko-Astound hi, please try new version and create a new ticket if issue is still valid. Thanks!
