### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/abadheshkumar/Library/Caches/JetBrains/WebStorm2022.3/index/fileincludes/.perFileVersion/indexed_versions/indexed_versions

### ISSUE THREAD

**Issue by akumarinfy** [smokeelow/intellij-sfcc#34]
IntelliJ build version: 2022.3.4 WS-223.8836.50
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1792x1120,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=com.intellij.util.io.PersistentEnumeratorBase$CorruptedException: PersistentEnumerator storage corrupted /Users/abadheshkumar/Library/Caches/JetBrains/WebStorm2022.3/index/fileincludes/.perFileVersion/indexed_versions/indexed_versions
	at com.intellij.util.io.PersistentEnumeratorBase.catchCorruption(PersistentEnumeratorBase.java:628)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:272)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:263)
	at com.intellij.util.io.PersistentMapImpl.doGet(PersistentMapImpl.java:587)
	at com.intellij.util.io.PersistentMapImpl.get(PersistentMapImpl.java:549)
	at com.intellij.util.io

**Comment by smokeelow** [comment]
hi @akumarinfy you can create a new ticket if this issue still valid in `2023.2`. Thanks
