### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by nx-olewolf** [smokeelow/intellij-sfcc#36]
IntelliJ build version: 2022.3.3 IU-223.8836.41
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.6
Plugin version: 2023.1
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,1920x1055,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.intellij.ui.ToolbarUtil$3@4a81515e,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:802)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1364)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at com.github.kittinunf.fuel.core.RequestExecutionOptions.submit(RequestExecutionOptions.kt:52)
	at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:224)
	at com.github.kittinunf.fuel.core.DeserializableKt.response(Deserializable.kt:106

**Comment by smokeelow** [comment]
hi, how many memory do you provide to the IDE ?

**Comment by smokeelow** [comment]
hi @nx-olewolf you can create a new ticket if this issue still valid in `2023.2`. Thanks
