### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached

### ISSUE THREAD

**Issue by maudebo** [smokeelow/intellij-sfcc#54]
IntelliJ build version: 2023.2 WS-232.8660.143
OS: Mac OS X
JDK: JetBrains s.r.o. 17.0.7
Plugin version: 2023.2.1.232
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,0,0,2859x1362,invalid,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
	at java.base/java.lang.Thread.start0(Native Method)
	at java.base/java.lang.Thread.start(Thread.java:802)
	at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1353)
	at java.base/java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1818)
	at java.base/java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:2033)
	at io.divetek.sfcc.util.JobSchedulersKt.forEachParallel(JobSchedulers.kt:171)
	at io.divetek.sfcc.util.JobSchedulersKt.forEachParallel$default(JobSchedulers.kt:163)

**Comment by smokeelow** [comment]
hi @maudebo  did you notice when this happened?
