### ISSUE TITLE
[IntelliJ][ReportedByUser] Uncaught Exception  java.lang.Throwable: TreeUI should be accessed only from EDT

### ISSUE THREAD

**Issue by tcerdan** [smokeelow/intellij-sfcc#58]
IntelliJ build version: 2023.3.2 WS-233.13135.92
OS: Windows 10
JDK: JetBrains s.r.o. 17.0.9
Plugin version: 2023.2.1.233
Additional Info: None
Parent component: 
```
com.intellij.openapi.wm.impl.IdeRootPane[,7,7,2561x1410,layout=com.intellij.openapi.wm.impl.IdeRootPane$MyRootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=449,maximumSize=,minimumSize=,preferredSize=]
```
Error message: 
```
IdeaLoggingEvent[message=null, throwable=java.lang.Throwable: TreeUI should be accessed only from EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.ui.tree.ui.DefaultTreeUI.isValid(DefaultTreeUI.java:216)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRowForPath(DefaultTreeUI.java:766)
	at java.desktop/javax.swing.JTree.getRowForPath(JTree.java:2281)
	at com.intellij.ui.treeStructure.Tree.collapsePath(Tree.java:629)
	at io.divetek.sfcc.ui.panel.SfccExplorer.collapseAll(SfccExplorer.kt:149)
	at io.divetek.sfcc.service.SfccExplorerService.expandSelectedConnection(SfccExplorerService.kt:530)
	at io.divetek.sfcc.system.BootstrapActivity$runActivity$1$1.invoke$lambda$1(BootstrapActivity.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at io.divetek.sfcc.system.BootstrapActivity$ru

**Comment by bhunter** [comment]
Glomming on to this ... getting the same error.
IntelliJ IDEA 2023.3.4 Build #IU-233.14475.28
Plugin version 2023.2.1.233

java.lang.Throwable: TreeUI should be accessed only from EDT
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.ui.tree.ui.DefaultTreeUI.isValid(DefaultTreeUI.java:216)
	at com.intellij.ui.tree.ui.DefaultTreeUI.getRowForPath(DefaultTreeUI.java:766)
	at java.desktop/javax.swing.JTree.getRowForPath(JTree.java:2281)
	at com.intellij.ui.treeStructure.Tree.collapsePath(Tree.java:629)
	at io.divetek.sfcc.ui.panel.SfccExplorer.collapseAll(SfccExplorer.kt:149)
	at io.divetek.sfcc.service.SfccExplorerService.expandSelectedConnection(SfccExplorerService.kt:530)
	at io.divetek.sfcc.system.BootstrapActivity$runActivity$1$1.invoke$lambda$1(BootstrapActivity.kt:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:878)
	at io.divetek.sfcc.system.BootstrapActivity$runActivity$1$1.invoke(BootstrapActivity.kt:25)
	at io.divetek.sfcc.system.BootstrapActivity$runActivity$1$1.invoke(BootstrapActivity.kt:24)
	at io.divetek.sfcc.util.JobSchedulersKt.onPooledThread$lambda$8(JobSchedulers.kt:90)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at com.intellij.util.concurrency.ContextCallable.call(ContextCallable.java:32)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.ContextRunnable.run(ContextRunnable.java:27)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by smokeelow** [comment]
hi @bhunter this error already fixed in upcoming release
